title: 
url: 
twitter: 
markdown: kramdown
plugins_dir: _plugins
data_dir: _data
layouts_dir: _layouts
includes_dir: _includes
sass:
  sass_dir: assets/css/_partials
  style: expanded
collections:
  navigation:
    output: true 
